<?php

namespace App\Infra\Repository\Configuration;

use App\Abstracts\AbstractRepository;
use App\Models\ReasonDelayVaccine;
use Illuminate\Database\Eloquent\Model;

class ReasonsVaccineDelayRepository extends AbstractRepository
{

    /**
     * @var Model
     */
    protected $model;

    public function __construct(ReasonDelayVaccine $model)
    {
        $this->model = $model;
    }

    // public function getPaginationList(array $params, array $with = [], int $perPage = null)
    // {
    //     return parent::getPaginationList($params, ['targetPublic']); // TODO: Change the autogenerated stub
    // }

    public function formatParams(array $params): array
    {
        return [
            'description' => $this->getAttribute($params, 'description'),
            'to' => $this->getAttribute($params, 'to'),
            'forwarding' => $this->getAttribute($params, 'forwarding'),
            'target_public_id' => $this->getAttribute($params, 'target_public_id'),
            'is_send_social_assistence' => false
        ];
    }

    /**
     * getByTargePublic function
     *
     * @param int $targetPublicId
     * @return void
     */
    public function getByTargetPublic(int $targetPublicId)
    {
        return $this->model->where('target_public_id', $targetPublicId)->get();
    }
}
